Project/ComputerShop/Models/order.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class order
    {
        public order()
        {
            this.delivery = new HashSet<delivery>();
            this.product = new HashSet<product>();
        }
       
        [Key]
        public int order_id { get; set; }

        public Nullable<System.DateTime> order_date { get; set; }
        public int userorder_id { get; set; }

        [Required]
        [Display(Name = "Способ оплаты")]
        public string payment_method { get; set; }
        [Required]
        [Display(Name = "Статус заказа")]
        public string orders_status { get; set; }

        public virtual ICollection<delivery> delivery { get; set; }
        public virtual ICollection<product> product { get; set; }

        [Range(1, int.MaxValue)]
        [Display(Name = "Итоговая сумма")]
        public Nullable<int> tax_sum { get; set; }
    }
}

Project/ComputerShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ComputerShop.Models;
using WebMatrix.WebData;
using ComputerShop.Filters;
using ComputerShop.DAO;
namespace ComputerShop.Controllers
{
    [InitializeSimpleMembership]
    public class OrderController : Controller
    {
        private DeliveryDAO deliveryDAO = new DeliveryDAO();
        private ComputerShopDBEntities db = new ComputerShopDBEntities();

        [Authorize(Roles = "Seller, Client")]
        public ActionResult Index()
        {
            int userID = WebSecurity.CurrentUserId;
            List<order> orders;
            if (User.IsInRole("Seller"))
            {
                orders = db.order.ToList();
            }
            else
            {
                orders = db.order.Where(order => order.userorder_id == userID).ToList();
                 
            }
            return View(orders);
        }


        [Authorize(Roles = "Client")]
        public ActionResult Create()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null || cart.IsEmpty())
            {
                return View("Empty");
            }
            int cost = 0;
            cart.Content.Keys.ToList().ForEach(key => cost += (int)db.product.Find(key).price * cart.Content[key]);
            ViewBag.cost = cost;
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection formCollection)
        {
            string paymethod = formCollection["method"];
            string deliveryType = formCollection["deliveryType"];
            string cost = formCollection["cost"];
            order order = new order();
            order.userorder_id = WebSecurity.CurrentUserId;
            order.order_date = DateTime.Now;
            order.payment_method = paymethod;
            order.tax_sum = Convert.ToInt32(cost);
            order.orders_status = "Оформлен";
            db.order.Add(order);
            db.SaveChanges();
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            ((Cart)Session["Cart"]).Clear();
            if (deliveryType.Equals("доставка на дом"))
            {
                return RedirectToAction("Create","Delivery");
            }
            else
            {
                return View("Thanks");
            }
        }

        [Authorize(Roles = "Seller, Client")]
        public ActionResult Delete(int id = 0)
        {
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Client") && WebSecurity.CurrentUserId != order.userorder_id)
            {
                return View("Error");
            }
            return View(order);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            bool flag = deliveryDAO.deleteDelivery(id);
            order order = db.order.Find(id);
            db.order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        [Authorize(Roles = "Client")]
        public ActionResult PayOrder(int id = 0)
        {
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost, ActionName("PayOrder")]
        public ActionResult SubmitPay(int id = 0)
        {
            order order = db.order.Find(id);
            order.orders_status = "Оплачен";
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Seller")]
        public ActionResult Submit(int id = 0)
        {
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        [HttpPost, ActionName("Submit")]
        public ActionResult SubmitConfirmed(int id = 0)
        {
            order order = db.order.Find(id);
            order.orders_status = "Подтвержден";
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Seller")]
        public ActionResult SubmitToDelivery(int id = 0)
        {
            order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }
        [HttpPost, ActionName("SubmitToDelivery")]
        public ActionResult SubmitToDeliveryConfirmed(int id = 0)
        {
            bool flag = deliveryDAO.confirmToDelivery(id);
            if (flag == true)
            {
                order order = db.order.Find(id);
                order.orders_status = "Выдан/отправлен";
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return RedirectToAction("Error");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/ComputerShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerShop.Models;

namespace ComputerShop.Controllers
{
    public class ProductController : Controller
    {
        private ComputerShopDBEntities db = new ComputerShopDBEntities();
        //
        // GET: /Product/

        public ActionResult Index(String searchString)
        {
            //выборка всех продуктов
            var products = from product in db.product
                           select product;

            int price = 0;
            //если @try = true, значит searchString - число (цена), если нет - название товара либо категории
            bool @try = int.TryParse(searchString, out price);

            //если searchString не пуст и @try - не число, значит фильтруем по категории либо по названию товара
            if (!String.IsNullOrEmpty(searchString) && !@try)
            {
                products = products.Where(s => s.product_name.Contains(searchString) || s.category.Contains(searchString));
            }
            //в противном случае, если searchString не пуст и @try - число, значит, фильтруем по цене
            else if (!String.IsNullOrEmpty(searchString) && @try)
            {
                products = products.Where(s => s.price <= price);
            }
            return View(products.ToList());
        }

        //
        // GET: /Product/Details/5

        public ActionResult Details(int id = 0)
        {
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /Product/Create

        public ActionResult Create()
        {
            ViewBag.productOrder_id = new SelectList(db.order, "order_id", "payment_method");

            return View();
        }

        //
        // POST: /Product/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(product product)
        {
            if (ModelState.IsValid)
            {
                db.product.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.productOrder_id = new SelectList(db.order, "order_id", "payment_method", product.productOrder_id);
            return View(product);
        }

        //
        // GET: /Product/Edit/5

        public ActionResult Edit(int id = 0)
        {
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.productOrder_id = new SelectList(db.order, "order_id", "payment_method", product.productOrder_id);
            return View(product);
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.productOrder_id = new SelectList(db.order, "order_id", "payment_method", product.productOrder_id);
            return View(product);
        }

        //
        // GET: /Product/Delete/5

        public ActionResult Delete(int id = 0)
        {
            product product = db.product.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Product/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.product.Find(id);
            db.product.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Project/ComputerShop/Views/Order/Create.cshtml
@{
    ViewBag.Title = "Разместить заказ";
}

<div class="content">
    <h2>Разместить заказ</h2>

    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Оформление заказа</legend>
            <p>С вас @ViewBag.cost рублей</p>
            <input id="cost" hidden="hidden" value="@ViewBag.cost" name="cost" type="text" />
              
            <label for="method">Способ оплаты:</label>
              <select id="method" name="method" required>
                <option value="Наличные">наличные</option>
                 <option value="Карта">карта</option>
             </select>
            <label for="deliveryType">Способ получения товара</label>
              <select id="deliveryType" name="deliveryType" required>
                <option value="доставка на дом">доставка на дом</option>
                 <option value="в магазине">в магазине</option>
             </select>

            
            <p>
                <input type="submit" value="Оформить" />
            </p>
        </fieldset>
    }

    <p>
        @Html.ActionLink("Вернуться", "Index")
    </p>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/ComputerShop/Views/Order/Delete.cshtml
@model ComputerShop.Models.order

@{
    ViewBag.Title = "Delete";
}

<div class="content">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>


    <div class="display-label">
        @Html.DisplayNameFor(model => model.userorder_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.userorder_id)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.order_date)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.order_date)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.orders_status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.orders_status)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.payment_method)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.payment_method)
    </div>

    @using (Html.BeginForm()) {
        <p>
            <input type="submit" value="Delete" />
            |
        @Html.ActionLink("Back to List", "Index")
        </p>
    }
</div>

Project/ComputerShop/Views/Order/Empty.cshtml
@{
    ViewBag.Title = "Ошибка. Корзина пуста.";
}

<div class="content"><p>Невозможно создать пустой заказ, пожалуйста добавьте @Html.ActionLink("товары", "Index", "Product") в корзину.</p></div>

Project/ComputerShop/Views/Order/Index.cshtml
@using ComputerShop.Models
@model IEnumerable<ComputerShop.Models.order>
@{
    ViewBag.Title = "Список заказов";
}

<div class="content">
    <h2>Список заказов</h2>
    <table class="data_table">
        <tr>
            <th>Дата создания</th>
            <th>Состояние заказа</th>
            <th>Способ оплаты</th>
            <th>Общая сумма заказа</th>
            <th>Список товаров</th>
            <th>Действия</th>
        </tr>
        @foreach (var item in Model) {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.order_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.orders_status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.payment_method)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tax_sum)
                </td>
                <td>
                    @foreach (var prod in item.product)
                    {
                        @prod
                    }
                </td>
                <td>
                   
                    @if (User.IsInRole("Seller") && item.orders_status.Equals("Оформлен")) {
                        @Html.ActionLink("Отменить", "Delete", new { id = item.order_id }) 
                        @Html.ActionLink("Подтвердить", "Submit", new { id = item.order_id })
                    }
                    else if (User.IsInRole("Seller") && item.orders_status.Equals("Оплачен")){
                         @Html.ActionLink("Выслать", "SubmitToDelivery", new { id = item.order_id }) 
                    }
                    else if (User.IsInRole("Seller") && item.orders_status.Equals("Выдан/отправлен")){
                         @Html.ActionLink("Удалить", "Delete", new { id = item.order_id }) 
                    }
                    else if (User.IsInRole("Client")) {
                        if (item.orders_status.Equals("Подтвержден")) {
                            @Html.ActionLink("Отменить", "Delete", new { id = item.order_id }) 
                            @Html.ActionLink("Оплатить","PayOrder", new { id = item.order_id})
                        }
                    }
                    else if (User.IsInRole("Client") && item.orders_status.Equals("Выдан/отправлен")){
                         @Html.ActionLink("Подтвердить", "Delete", new { id = item.order_id }) 
                    }
                </td>
            </tr>
        }
    </table>
    @if (User.IsInRole("Client")) {
        <p>
            @Html.ActionLink("Оформить заказ", "Index", "Cart")
        </p>
    }
</div>

Project/ComputerShop/Views/Order/PayOrder.cshtml
@model ComputerShop.Models.order

@{
    ViewBag.Title = "Оплатить заказ";
}
<div class="content">
    @using (Html.BeginForm(new { id = Model.order_id })) {
        <input type="submit" value="Оплатить" />
    }
</div>

Project/ComputerShop/Views/Order/Submit.cshtml
@model ComputerShop.Models.order

@{
    ViewBag.Title = "Подтвердить заказ";
}
<div class="content">
    <h2>Вы действительно хотите подтвердить заказ?</h2>
    @using (Html.BeginForm(new { id = Model.order_id })) {
        <input type="submit" value="Подтвердить" />
    }
</div>

Project/ComputerShop/Views/Order/SubmitToDelivery.cshtml
@model ComputerShop.Models.order

@{
    ViewBag.Title = "Подтвердить отправку";
}
<div class="content">
    <h2>Вы действительно хотите подтвердить отправку заказа?</h2>
    @using (Html.BeginForm(new { id = Model.order_id })) {
        <input type="submit" value="Подтвердить" />
    }
</div>

Project/ComputerShop/Views/Order/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<div class="content">
    Спасибо за покупку!!!
    <p>@Html.ActionLink("Посмотреть заказ", "Index", "Order")</p></div>